blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 博客列表
    path('list/', views.blog_list, name='list'),
    # 删除博客
    path('delete/', views.blog_delete, name='delete'),
    # 修改博客
    path('edit/', views.blog_edit, name='edit'),
    # 博客新增
    path('add/', views.blog_add, name='add'),
    # 博客分析
    path('analysis/', views.blog_analysis, name='analysis'),
]

blog_admin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 后台管理系统的路由
    path('admin/', admin.site.urls),

    # 包含用户应用的子路由
    path('user/', include("user.urls")),
    # 包含博客应用的子路由
    path('blog/', include("blog.urls")),
    path('', include("index.urls")),
]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    # 首页
    path('', views.index, name='index'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # 注册
    path('register/', views.register, name='register'),
    # 登录
    path('login/', views.login_view, name="login"),
    # 注销
    path('logout/', views.logout_view, name="logout"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

# 自定义验证器，最低长度不小于30
content_validator = MinLengthValidator(limit_value=30, message="文章的长度不能小于30个字符")


class Blog(models.Model):
    """
    博客模型
    """
    # 标题
    title = models.CharField(max_length=250)  # varchar

    # 内容
    content = models.TextField(validators=[content_validator])  # text

    # 点赞数量
    good_num = models.IntegerField(default=0)

    # 踩数量
    bad_num = models.IntegerField(default=0)

    # 阅读数量
    view_num = models.IntegerField(default=0)

    # 发布时间
    date_published = models.DateTimeField(default=timezone.now)  # datetime

    # 作者
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 级联删除

    def __str__(self):
        return self.title

index/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from blog_admin import settings
from .models import Blog


def blog_add(request):
    context = {
        "username": settings.username,
        "title": "添加博客"
    }
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")
        try:
            Blog.objects.create(title=title, content=content, author_id=settings.user_id)
            return redirect(reverse("blog:list"))
        except Exception as e:
            print(e)
            context["msg"] = "添加博客失败"
            return render(request, "error.html", context)
    return render(request, "blog/add.html", context)


def blog_list(request):
    context = {
        "username": settings.username,
        "title": "博客管理"
    }

    # 始终能够优先拿到最新的文章
    blogs = Blog.objects.all().order_by("-id")
    try:
        # 默认是第1页
        page = int(request.GET.get("page", 1))
        context["current_page"] = page

        # 每页数量
        size = int(request.GET.get("size", 3))
        context["size"] = size

        # 开始索引
        offset = (page - 1) * size

        # 总数
        total = blogs.count()

        # 总页数
        total_page = 0
        if total % size == 0:
            total_page = total // size
        else:
            total_page = total // size + 1

        # 计算下一页和上一页
        has_next = True
        if page >= total_page:
            has_next = False
        has_prev = True
        if page <= 1:
            has_prev = False
        context["has_next"] = has_next
        context["next_page"] = page + 1
        context["has_prev"] = has_prev
        context["prev_page"] = page - 1

        # 中间页码
        middle_pages = list(range(1, total_page + 1))
        context["middle_pages"] = middle_pages

        # 向前端传递
        context['blogs'] = blogs[offset:offset + size]
        return render(request, "blog/list.html", context)
    except Exception as e:
        print(e)
        context['msg'] = "参数错误，请检查page或size的值是否正确"
        return render(request, "error.html", context)


def blog_delete(request):
    context = {}
    blog_id = request.GET.get('id')
    try:
        Blog.objects.get(id=blog_id).delete()
    except:
        context['msg'] = "要删除的数据不存在"
        return render(request, "error.html", context)
    return redirect(reverse('blog:list'))


def blog_edit(request):
    context = {}

    # 执行修改
    if request.method == 'POST':
        blog_id = request.POST.get('id')
        title = request.POST.get('title')
        content = request.POST.get('content')
        try:
            blog = Blog.objects.get(id=blog_id)
            blog.title = title
            blog.content = content
            blog.save()
            return redirect(reverse('blog:list'))
        except:
            context['msg'] = "要修改的数据不存在"
            return render(request, "error.html", context)

    # 渲染修改页面
    blog_id = request.GET.get('id')
    try:
        blog = Blog.objects.get(id=blog_id)
        context['blog'] = blog
    except:
        context['msg'] = "要修改的数据不存在"
        return render(request, "error.html", context)
    return render(request, 'blog/edit.html', context)


def blog_analysis(request):
    context = {
        "username": settings.username,
        "title": "文章分析"
    }
    blogs = Blog.objects.all().order_by('-good_num')[:6]

    # 所有文章的名字
    # x = [blog.title[:5] for blog in blogs]
    x = [blog.id for blog in blogs]
    # x = "$$$".join(x)
    # print(x, type(x))
    context["x"] = x

    # 每篇文章的点赞数量
    y = [blog.good_num for blog in blogs]
    context["y"] = y

    # 执行修改
    return render(request, 'blog/analysis.html', context)

index/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from blog_admin import settings


def index(request):
    """
    首页视图函数
    :param request:
    :return:
    """
    # 登录校验
    # if not settings.username:
    #     return redirect(reverse('user:login'))

    context = {"username": settings.username}
    return render(request, "index.html", context)

user/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from blog_admin import settings
from django.contrib.auth import authenticate, login, logout


def register(request):
    """
    注册视图函数
    :param request:
    :return:
    """
    context = {}
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        re_password = request.POST.get('re_password')

        # 用户名和密码校验
        if username == "":
            return render(request, "error.html", {"msg": "用户名不能为空"})
        if password == "":
            return render(request, "error.html", {"msg": "密码不能为空"})
        if len(username) < 3:
            return render(request, "error.html", {"msg": "用户名长度不能小于3"})
        if len(password) < 3:
            return render(request, "error.html", {"msg": "密码长度不能低于6位"})

        # TODO：安全性、数字、字母、大小写、符号

        # 两次密码校验
        if password == re_password:
            try:
                User.objects.create_user(username=username, password=password)
                return redirect(reverse('user:login'))
            except:
                return render(request, "error.html", {"msg": "该用户已存在"})

    return render(request, "user/register.html", context)


def login_view(request):
    """
    登录视图函数
    :param request:
    :return:
    """
    # 要给前端渲染的数据
    context = {}

    # POST请求，登录校验
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        # 查有没有用户
        try:
            user = User.objects.get(username=username)
            if user is not None:
                # 校验用户名和密码
                user = authenticate(username=username, password=password)

                # 登录成功以后，跳转到首页
                settings.username = username
                settings.user_id = user.id
                if user.is_active:
                    login(request, user)  # 进行登陆操作，完成session的设置
                    return redirect(reverse("index:index"))
            context["error"] = "用户名或密码错误"
        except:
            context["error"] = "该用户不存在"

    # GET请求：渲染登录页面
    return render(request, "user/login.html", context)


def logout_view(request):
    """
    注销视图函数
    :param request:
    :return:
    """
    logout(request)
    return redirect(reverse('user:login'))

templates/blog/add.html
{% extends "layout/base.html" %}
{% block content %}
    <div class="card card-primary">
        <form action="{% url 'blog:add' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ blog.id }}">
            <div class="card-body">
                <div class="form-group">
                    <label for="title">标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="content">内容</label>
                    <textarea type="password" class="form-control" id="content" name="content"
                              rows="12">
                                        </textarea>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">提交</button>
            </div>
        </form>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
{% endblock %}

templates/blog/analysis.html
{% extends 'layout/base.html' %}
{% block content %}
    <div id="data" style="display: none;">{{ x }}</div>
    <div id="main" style="width: 100%;height:480px;text-align:center;"></div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        let xData = document.getElementById('data').innerText
        let dataArr = xData.split("$$$")
        console.log(xData);
        console.log(dataArr);

        myChart.setOption({
            xAxis: {
                //data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
                //data: dataArr
                data: {{x}}
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
                //data: [5, 20, 36, 10, 10, 20]
                data: {{ y }}
            }]
        })
    </script>
{% endblock %}

templates/blog/edit.html
{% extends 'layout/base.html' %}
{% block content %}
    <div class="card card-primary">
        <form action="{% url 'blog:edit' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ blog.id }}">
            <div class="card-body">
                <div class="form-group">
                    <label for="title">标题</label>
                    <input type="text" class="form-control" id="title" value="{{ blog.title }}" name="title">
                </div>
                <div class="form-group">
                    <label for="content">内容</label>
                    <textarea type="password" class="form-control" id="content" name="content" rows="12">
                                            {{ blog.content }}
                                        </textarea>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">提交</button>
            </div>
        </form>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
{% endblock %}

templates/blog/list.html
{% extends 'layout/base.html' %}

templates/error.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#公共头部开始#}
<header>
    <ul>
        <li><a href="{% url 'index:index' %}">首页</a></li>

        {#如果登录了#}
        {% if username %}
            <li><a href="">{{ username }}</a></li>
            <li><a href="">注销</a></li>
        {% else %}
            <li><a href="{% url 'user:login' %}">登录</a></li>
            <li><a href="{% url 'user:register' %}">注册</a></li>
        {% endif %}
    </ul>
</header>
{#公共头部结束#}

<h1>抱歉，系统发生了错误</h1>
<p style="color: red">{{ msg }}</p>
</body>
</html>

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Simple Tables</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/mdist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
    <!--顶部导航开始-->
    {% include "layout/top.html" %}
    <!--顶部导航结束-->

    {#左侧导航开始#}
    {% include "layout/left.html" %}
    {#左侧导航结束#}

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ title }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item">
                                <a href="{% url 'index:index' %}">首页</a></li>
                            <li class="breadcrumb-item active">{{ title }}</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        {#个性内容开始#}
                        {% block content %}
                            <div class="card">
                                {#操作栏开始#}
                                <div class="card-header">
                                    <a href="{% url 'blog:add' %}"
                                       class="btn btn-sm btn-primary">
                                        新增
                                    </a>
                                </div>
                                {#操作栏结束#}

                                {#表格开始#}
                                <div class="card-body">
                                    <table class="table table-bordered">
                                        <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>标题</th>
                                            <th>作者</th>
                                            <th style="width: 120px">操作</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for blog in blogs %}
                                            <tr>
                                                <td>{{ blog.id }}</td>
                                                <td>{{ blog.title }}</td>
                                                <td>{{ blog.author.username }}</td>
                                                <td class="text-center row">
                                                    <a href="{% url 'blog:edit' %}?id={{ blog.id }}"
                                                       class="btn btn-sm btn-warning">编辑</a>
                                                    <a href="{% url 'blog:delete' %}?id={{ blog.id }}"
                                                       class="btn btn-sm btn-danger" style="margin-left: 5px;">删除</a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                {#表格结束#}

                                {#分页开始#}
                                <div class="card-footer clearfix">
                                    <ul class="pagination pagination-sm m-0 float-right">
                                        {% if has_prev %}
                                            <li class="page-item">
                                                <a class="page-link"
                                                   href="{% url 'blog:list' %}?page={{ prev_page }}&size={{ size }}">
                                                    上一页</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="#">上一页</a></li>
                                        {% endif %}
                                        {#中间页码#}
                                        {% for middle_page in middle_pages %}
                                            <li class="page-item">
                                                <a class="page-link"
                                                   href="{% url 'blog:list' %}?page={{ middle_page }}&size={{ size }}">
                                                    {{ middle_page }}
                                                </a>
                                            </li>
                                        {% endfor %}
                                        {% if has_next %}
                                            <li class="page-item">
                                                <a class="page-link"
                                                   href="{% url 'blog:list' %}?page={{ next_page }}&size={{ size }}">
                                                    下一页</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="#">下一页</a></li>
                                        {% endif %}

                                    </ul>
                                </div>
                                {#分页结束#}
                            </div>
                        {% endblock %}
                        {#个性内容结束#}
                    </div>
                </div>
            </div>
        </section>
    </div>

    {#底部开始#}
    {% include "layout/footer.html" %}
    {#底部结束#}

</div>
<script src="/static/plugins/jquery/jquery.min.js"></script>
<script src="/static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/static/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
<script src="/static/mdist/js/adminlte.min.js"></script>
<script src="/static/mdist/js/demo.js"></script>
<script src="/static/js/echarts.min.js"></script>
{% block scripts %}

{% endblock %}
</body>
</html>

templates/layout/footer.html
{#底部开始#}
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        zhangdapeng@qq.com
    </div>
    <strong>版权所有 &copy; 2022 <a href="https://github.com/zhangdapeng520/">张大鹏</a></strong>
</footer>
{#底部结束#}

templates/layout/left.html
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!--品牌LOGO-->
    <a href="{% url 'index:index' %}" class="brand-link">
        <img src="/static/mdist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">大鹏管理系统</span>
    </a>

    <!--侧边栏开始-->
    <div class="sidebar">
        <!--侧边导航-->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-table"></i>
                        <p>
                            数据管理
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'blog:list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>博客管理</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-table"></i>
                        <p>
                            数据分析
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'blog:analysis' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>文章分析</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
    <!--侧边栏结束-->
</aside>

templates/layout/top.html
<!--顶部导航开始-->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!--左侧链接-->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'index:index' %}" class="nav-link">首页</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">联系人</a>
        </li>
    </ul>

    <!--右侧链接-->
    <ul class="navbar-nav ml-auto">
        {#如果登录了#}
        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="#" role="button">
                    {{ request.user }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="{% url 'user:logout' %}" role="button">
                    注销
                </a>
            </li>
        {% else %}
            <!--注册-->
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="{% url 'user:register' %}" role="button">
                    注册
                </a>
            </li>

            <!--登录-->
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="{% url 'user:login' %}" role="button">
                    登录
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
<!--顶部导航结束-->

templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Log in</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="/static/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/mdist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="{% url 'index:index' %}"><b>大鹏</b>后台管理系统</a>
    </div>
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">请输入用户名和密码</p>
            <form action="{% url 'user:login' %}" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="用户名" name="username">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="密码" name="password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">立即登录</button>
                    </div>
                </div>
            </form>
            <p class="mb-0">
                <a href="{% url 'user:register' %}" class="text-center">注册新账号</a>
            </p>
        </div>
    </div>
</div>

<!-- jQuery -->
<script src="/static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/mdist/js/adminlte.min.js"></script>
</body>
</html>

templates/user/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Registration Page</title>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="/static/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/mdist/css/adminlte.min.css">
</head>
<body class="hold-transition register-page">
<div class="register-box">
    <div class="register-logo">
        <a href="{% url 'index:index' %}"><b>大鹏</b>后台管理系统</a>
    </div>

    <div class="card">
        <div class="card-body register-card-body">
            <p class="login-box-msg">注册新账号</p>
            <form action="{% url 'user:register' %}" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="用户名" name="username">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="密码" name="password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="确认密码" name="re_password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">立即注册</button>
                    </div>
                </div>
            </form>

            <a href="{% url 'user:login' %}" class="text-center">登录</a>
        </div>
    </div>
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="/static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/mdist/js/adminlte.min.js"></script>
</body>
</html>